//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBiblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tworcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tworcy()
        {
            this.Ksiazki = new HashSet<Ksiazki>();
        }
    
        public int idTworcy { get; set; }
        public string nazwiskoTworcy { get; set; }
        public string imieTworcy { get; set; }
        public Nullable<int> rokUrodzenia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ksiazki> Ksiazki { get; set; }

        public override string ToString()
        {
            if (rokUrodzenia == null)
            {
                return $"{imieTworcy} {nazwiskoTworcy} (rok urodzenia nieznany)";
            }
            return $"{imieTworcy} {nazwiskoTworcy} (urodzony {rokUrodzenia})";
        }
    }
 
}
